CREATE DATABASE IF NOT EXISTS rsTest;

USE rsTest;

CREATE TABLE IF NOT EXISTS TestTable
(
    id      INT AUTO_INCREMENT,
    title   VARCHAR(255) NOT NULL,
    content VARCHAR(255),
    author  VARCHAR(80)  NOT NULL,
    PRIMARY KEY (id)
);